"""create_clients_table

Revision ID: 0bead93268c4
Revises: ef76fa36aa95
Create Date: 2025-05-22 21:12:22.216513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bead93268c4'
down_revision: Union[str, None] = 'ef76fa36aa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(), nullable=False))
    op.add_column('products', sa.Column('section', sa.String(), nullable=False))
    op.add_column('products', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.alter_column('products', 'status',
               existing_type=postgresql.ENUM('in_stock', 'restocking', 'out_of_stock', name='productstatus'),
               type_=sa.Enum('in_stock', 'restocking', 'out_of_stock', name='productstatusenum'),
               existing_nullable=False)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.alter_column('products', 'status',
               existing_type=sa.Enum('in_stock', 'restocking', 'out_of_stock', name='productstatusenum'),
               type_=postgresql.ENUM('in_stock', 'restocking', 'out_of_stock', name='productstatus'),
               existing_nullable=False)
    op.drop_column('products', 'images')
    op.drop_column('products', 'expiration_date')
    op.drop_column('products', 'section')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
