"""add_address_fields_to_client

Revision ID: 286705d3f228
Revises: 43ecb4704dbd
Create Date: 2025-05-23 19:48:57.140091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286705d3f228'
down_revision: Union[str, None] = '43ecb4704dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('street', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('number', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('complement', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('neighborhood', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('city', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('state', sa.String(length=2), nullable=False))
    op.add_column('clients', sa.Column('zip_code', sa.String(length=8), nullable=False))
    op.add_column('clients', sa.Column('cpf', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_cpf'), 'clients', ['cpf'], unique=True)
    op.drop_column('clients', 'address')
    # op.alter_column('orders', 'status',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatusenum'),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('clients', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_cpf'), table_name='clients')
    op.drop_column('clients', 'cpf')
    op.drop_column('clients', 'zip_code')
    op.drop_column('clients', 'state')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'neighborhood')
    op.drop_column('clients', 'complement')
    op.drop_column('clients', 'number')
    op.drop_column('clients', 'street')
    # ### end Alembic commands ###
