"""add created_by_user to orders

Revision ID: 43ecb4704dbd
Revises: 6220b6fba61a
Create Date: 2025-05-23 17:28:11.899919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ecb4704dbd'
down_revision: Union[str, None] = '6220b6fba61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'orders', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'created_by_user_id')
    # ### end Alembic commands ###
