"""associate orders with clients

Revision ID: 6220b6fba61a
Revises: fd62833671a3
Create Date: 2025-05-23 17:24:46.119684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6220b6fba61a'
down_revision: Union[str, None] = 'fd62833671a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'])
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'client_id')
    # ### end Alembic commands ###
