"""Add active and created_at columns to products

Revision ID: e66bcf914191
Revises: c9d445fea41e
Create Date: 2024-11-07 14:55:58.737684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66bcf914191'
down_revision: Union[str, None] = 'c9d445fea41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'active')
    # ### end Alembic commands ###
